version: '3.6'

services:

   mysql:
    image: percona/percona-server:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_db
    restart: always

  laravel:
    image: registry.bizmates.com/docker/laravel:prod
    container_name: laravel
    ports:
      - 80:80
    links:
      - mysql
    restart: always
    privileged: true
    tty: true
